export type TechIcon = { slug: string; label: string };

export const TECH_ICONS: TechIcon[] = [
  { slug: 'nextdotjs', label: 'Next.js' },
  { slug: 'react', label: 'React' },
  { slug: 'typescript', label: 'TypeScript' },
  { slug: 'javascript', label: 'JavaScript' },
  { slug: 'nodedotjs', label: 'Node.js' },
  { slug: 'python', label: 'Python' },
  { slug: 'go', label: 'Go' },
  { slug: 'rust', label: 'Rust' },
  { slug: 'php', label: 'PHP' },
  { slug: 'cplusplus', label: 'C++' },
  { slug: 'dotnet', label: '.NET' },
  { slug: 'kotlin', label: 'Kotlin' },
  { slug: 'swift', label: 'Swift' },
  { slug: 'dart', label: 'Dart' },
  { slug: 'flutter', label: 'Flutter' },
  { slug: 'tailwindcss', label: 'Tailwind CSS' },
  { slug: 'html5', label: 'HTML5' },
  { slug: 'css', label: 'CSS3' },
  { slug: 'svelte', label: 'Svelte' },
  { slug: 'angular', label: 'Angular' },
  { slug: 'vuedotjs', label: 'Vue' },
  { slug: 'nuxt', label: 'Nuxt' },
  { slug: 'astro', label: 'Astro' },
  { slug: 'remix', label: 'Remix' },
  { slug: 'redux', label: 'Redux' },
  { slug: 'reactquery', label: 'React Query' },
  { slug: 'docker', label: 'Docker' },
  { slug: 'kubernetes', label: 'Kubernetes' },
  { slug: 'linux', label: 'Linux' },
  { slug: 'ubuntu', label: 'Ubuntu' },
  { slug: 'debian', label: 'Debian' },
  { slug: 'gnubash', label: 'Bash' },
  { slug: 'shell', label: 'Shell' },
  { slug: 'nginx', label: 'Nginx' },
  { slug: 'git', label: 'Git' },
  { slug: 'github', label: 'GitHub' },
  { slug: 'gitlab', label: 'GitLab' },
  { slug: 'githubactions', label: 'GitHub Actions' },
  { slug: 'postgresql', label: 'PostgreSQL' },
  { slug: 'mysql', label: 'MySQL' },
  { slug: 'mongodb', label: 'MongoDB' },
  { slug: 'redis', label: 'Redis' },
  { slug: 'supabase', label: 'Supabase' },
  { slug: 'firebase', label: 'Firebase' },
  { slug: 'prisma', label: 'Prisma' },
  { slug: 'graphql', label: 'GraphQL' },
  { slug: 'apollographql', label: 'Apollo GraphQL' },
  { slug: 'express', label: 'Express' },
  { slug: 'electron', label: 'Electron' },
  { slug: 'tauri', label: 'Tauri' },
  { slug: 'vercel', label: 'Vercel' },
  { slug: 'vite', label: 'Vite' },
  { slug: 'webpack', label: 'Webpack' },
  { slug: 'eslint', label: 'ESLint' },
  { slug: 'prettier', label: 'Prettier' },
  { slug: 'npm', label: 'npm' },
  { slug: 'pnpm', label: 'pnpm' },
  { slug: 'yarn', label: 'Yarn' },
  { slug: 'jest', label: 'Jest' },
  { slug: 'cypress', label: 'Cypress' },
  { slug: 'figma', label: 'Figma' },
  { slug: 'googlecloud', label: 'Google Cloud' },
  { slug: 'stripe', label: 'Stripe' },
  { slug: 'zod', label: 'Zod' },
];

export function techIcon(slug: string): TechIcon | undefined {
  return TECH_ICONS.find((i) => i.slug === slug);
}

export function iconUrl(slug: string) {
  return `https://cdn.simpleicons.org/${encodeURIComponent(slug)}`;
}
